name: Deploy Backend to OnRender

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'  # Optional: Trigger only when the 'server' folder is modified
jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # cd server  # If your server is inside the "server" folder, ensure you're in the correct directory
          npm install

      - name: Deploy to OnRender
        env:
          ONRENDER_TOKEN: ${{ secrets.ONRENDER_TOKEN }}
        run: |
          curl -X POST "https://api.onrender.com/v1/services/YOUR_SERVICE_ID/deploy" \
            -H "Authorization: Bearer $ONRENDER_TOKEN"
